Todo-Pallets/Models/Mensajes.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;


namespace Todo_Pallets.Models
{
	public class Mensajes
	{
		private int id;
		private String nombre;
		private String apellido;
		private String email;
		private String consulta;

		public Mensajes(int id, string nombre, string apellido, string email, string consulta)
		{
			this.id = id;
			this.nombre = nombre;
			this.apellido = apellido;
			this.email = email;
			this.consulta = consulta;
		}

		#region -gets-

		public int getID() { return id; }
		public String getNombre() {	return nombre; }
		public String getApellido() { return apellido; }
		public String getEmail() { return email; }
		public String getConsulta() {	return consulta; }

		#endregion

	}

	public static class Chequeo
	{ 
		public static string pagina { get; set; }
	}
}

Todo-Pallets/Controllers/MensajeController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Web.Mvc;
using System.Net;
using System.Net.Mail;
using System.Data.SqlClient;
using Todo_Pallets.Models;


namespace Todo_Pallets.Controllers
{
	public class MensajeController : Controller
  {

		public ActionResult MandarMensaje(String nombre, String apellido, String edad, String email, String emailPadres, String consulta, String ofertasNovedades)
			{
				#region -Validando datos formulario-
				// Chequeando si edad contiene algún número, usando try-catch por si surge un error:
				int edadParseada = 0; 
				
				try
				{
					edadParseada = Int32.Parse(edad); 
				}
				catch
				{ 
					ViewBag.resultadoMensaje = "Error: La edad tiene que ser si o si un número (edad = " + edad + " ).";
					return View();
				}

				// Chequeando si el campo nombre tiene algo escrito:
				if (String.IsNullOrEmpty(nombre))
				{
					ViewBag.resultadoMensaje = "Error: El campo \"nombre\" está vacío (nombre = " + nombre + ")."; 
					return View();
				}

				// Chequeando si el campo apellido tiene algo escrito:
				if (String.IsNullOrEmpty(apellido))
				{
					ViewBag.resultadoMensaje = "Error: El campo \"Apellido\" está vacío (apellido = " + apellido + ")."; 
					return View();
				}

				// Chequeando si el campo email tiene algo escrito:
				if (String.IsNullOrEmpty(email))
					{
						ViewBag.resultadoMensaje = "Error: El campo \"Email\" está vacío (email = " + email + ").";
						return View();
					}

				// Chequeando si el campo email tiene arroba y punto:
				if (!(email.Contains("@") && email.Contains(".")))
					{
						ViewBag.resultadoMensaje = "Error: El campo \"Email\" no contiene arroba o no contiene punto alguno (email = " + email + ")."; 
						return View();
					}

				// Chequeando si el campo edad es menor a '14':
				if (edadParseada < 14)
				{
					// Chequeando si el campo "email de los padres" tiene algo escrito:
					if (String.IsNullOrEmpty(emailPadres))
					{
						ViewBag.resultadoMensaje = "Error: El campo \"Email de los Padres\" está vacío (email padres = " + emailPadres + ")."; 
						return View();
					}

					// Chequeando si el campo "email de los padres" tiene arroba y punto:
					if (!(emailPadres.Contains("@") && emailPadres.Contains(".")))
					{
						ViewBag.resultadoMensaje = "Error: El campo \"Email de los Padres\" no contiene arroba o no contiene punto alguno (email padres = " + emailPadres + ").";
						return View();
					}
				}

				// Chequeando si el campo consulta tiene algo escrito:
				if (String.IsNullOrEmpty(consulta))
				{
					ViewBag.resultadoMensaje = "Error: El campo \"Consulta\" está vacío (consulta = " + consulta + ")."; 
					return View();
				}
			#endregion

				#region -Conexión a BD-
				// ----------------------------------------
				// Conectado con la base de datos (BD):
				// ----------------------------------------

				// Esta variable guarda los datos necesarios para conectarse a la BD:
				string connectionString = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;

				SqlConnection connection = new SqlConnection(connectionString);

				try
				{
					connection.Open();

					// Hacemos el ingreso de datos a la tabla correspondiente:
					string sqlTemplate = @"INSERT INTO TodoPallets.dbo.FormularioContacto
																						 (nombre,apellido,edad,email,emailPadres,consulta)
																			 VALUES
																						 ('{0}','{1}','{2}','{3}','{4}','{5}')";

					string sqlQuery = String.Format(sqlTemplate, nombre, apellido, edad, email, emailPadres, consulta);

					SqlCommand command = new SqlCommand(sqlQuery, connection);
					int affectedRows = command.ExecuteNonQuery();

					// Cerrando la conexión con la BD:
					command.Dispose();
					connection.Close();
				}
				catch (Exception /*problemaBD*/)
				{
					// No poner nada acá.
					// return "Error: hay algún problema con el ingreso de datos a la BD (problema: " + problemaBD + ").";
				}
			#endregion

				#region -Enviando Mail-
				// ----------------------------------------------------------------------
				// Enviado mail desde cuenta de gmail (a partir de envio de formulario):
				// ----------------------------------------------------------------------

				try
				{
					// Pasando dirección de mensaje de la persona que realiza la consulta,
					// usando su nombre y apellido que completó en el formulario de contacto:
					string desde = nombre + " " + apellido;
					MailAddress from = new MailAddress(email, desde);

					// Pasando dirección de mensaje de la empresa:
					MailAddress to = new MailAddress("todo.pallets.consultas@gmail.com");

					// Mensaje y título:
					MailMessage mail = new MailMessage(from, to);
					mail.Subject = ConfigurationManager.AppSettings["ContactMailSubject"];

					// El cuerpo del mensaje del formulario de contacto se copiará al cuerpo del mail:
					string cuepoMensaje = "Consulta desde formulario:\n\n- Nombre: {0}\n- Apellido: {1}\n- Edad: {2}\n- Email: {3}\n- Email de padres: {4}\n\n- Consulta: {5}";
					string elMensaje = String.Format(cuepoMensaje, nombre, apellido, edad, email, emailPadres, consulta);

			 		mail.Body = elMensaje;
					mail.IsBodyHtml = false;

					// Envío:
					string host = ConfigurationManager.AppSettings["ContactMailSMTPHost"];
					int port = Int32.Parse(ConfigurationManager.AppSettings["ContactMailSMTPPort"]);
					string usuario = ConfigurationManager.AppSettings["ContactMailSMTPUsername"];
					string contraseña = ConfigurationManager.AppSettings["ContactMailSMTPPassword"];

					SmtpClient smtp = new SmtpClient(host, port);
					smtp.UseDefaultCredentials = false;
					smtp.Credentials = new NetworkCredential(usuario, contraseña);
					smtp.EnableSsl = true;
					smtp.Send(mail);
				}
				catch (Exception problemaSMTP)
				{
					ViewBag.resultadoMensaje = "Error: No se ha podido enviar mensaje a casilla de gmail (problema: " + problemaSMTP + ").";
					return View();
				}
			
				// Si todo lo anterior está bien, se devuelve una confirmacion al usuario:
				ViewBag.resultadoMensaje = "Su consulta ha sido enviada con total éxito!\nEn la brevedad nos contactaremos con ud.";

				#endregion

				return View();
		}


		public ActionResult ListaMensaje()
    {
			List<Mensajes> lstDetalle = new List<Mensajes>();
			// Esta variable guarda los datos necesarios para conectarse a la BD:
			string connectionString = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;

			// La consulta:
			string sql = @"SELECT * FROM TodoPallets.dbo.FormularioContacto WHERE deleted = 0";

			SqlConnection connection = new SqlConnection(connectionString);

      try
      {
				// Iniciando conexión con la BD:
        connection.Open();

				// Creando un objeto para unir la query SQL con la conexion a la BD:
        SqlCommand command = new SqlCommand(sql, connection);
				// Se ejecuta el comando:
        SqlDataReader dataReader = command.ExecuteReader();

				// El 'while' entra una vez por cada fila que es retornada por la query:
				while (dataReader.Read())
        {
					// Al 'dataReader' le preguntamos por la info de cada columna de la fila actual:
          int mensajeId = (int)dataReader["id"];
          string nombre = dataReader["nombre"].ToString();
          string apellido = dataReader["apellido"].ToString();
          string email = dataReader["email"].ToString();

					Mensajes detalle = new Mensajes(mensajeId, nombre, apellido, email, string.Empty);
          lstDetalle.Add(detalle);
        }

				// Cerrando la conexión con la BD:
        dataReader.Close();
        command.Dispose();
        connection.Close();
      }
      catch (Exception /*problemaLM*/)
      {
				// No poner nada acá.
				// return "Error: hay algún problema con el ingreso de datos a la BD (problema: " + problemaLM + ").";
      }

      ViewBag.lstMensajes = lstDetalle;

			// Pasando tipo de página, para la sección de 'BorrarMensajes':

			Chequeo.pagina = "LM";

			return View();
    }


		public ActionResult DetalleMensaje(string id)
		{
			// Esta variable guarda los datos necesarios para conectarse a la BD:
			string connectionString = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;

			// La consulta:
			string sql = @"SELECT * FROM TodoPallets.dbo.FormularioContacto	WHERE deleted = 0 AND id=" + id;

			SqlConnection connection = new SqlConnection(connectionString);
			try
			{
				// Iniciando conexión con la BD:
				connection.Open();

				SqlCommand command = new SqlCommand(sql, connection);
				SqlDataReader dataReader = command.ExecuteReader();

				if (dataReader.Read())
				{
					// Al 'dataReader' le preguntamos por la info de cada columna de la fila actual:
					int mensajeId = (int)dataReader["id"];
					string nombre = dataReader["nombre"].ToString();
					string apellido = dataReader["apellido"].ToString();
					string email = dataReader["email"].ToString();
					string consulta = dataReader["consulta"].ToString();

					Mensajes detalle = new Mensajes(mensajeId, nombre, apellido, email, consulta);
					ViewBag.mensaje = detalle;
				}

				// Cerrando la conexión con la BD:
				dataReader.Close();
				command.Dispose();
				connection.Close();
			}
			catch (Exception /*problemaDM*/)
			{
				// No poner nada acá.
				// return "Error: hay algún problema con el ingreso de datos a la BD (problema: " + problemaMD + ").";
			}
			return View();
		}


		public ActionResult BorrarMensaje(string id)
		{
			// Esta variable guarda los datos necesarios para conectarse a la BD:

Todo-Pallets/Views/Mensaje/BorrarMensaje.cshtml
@using Todo_Pallets.Models;

@{
	ViewBag.Titulo = "Borrar Mensaje";
}


<section>
	<div class="row">
		<div id="columna-descripcion-acerca">
			<div class="col-sm-6 columna">

				<h1 id="descripcion">Borrando mensaje:</h1>
				<p class="parrafo-descripcion"><b>Resultado:</b> @ViewBag.resultadoMensaje</p>

				@if(Chequeo.pagina == "LM")
				{
					<p class="parrafo-descripcion">@Html.ActionLink("Volver", "ListaMensaje", "Mensaje")</p>
					Chequeo.pagina = "";
        }
				else if(Chequeo.pagina == "LYDM")
				{
					<p class="parrafo-descripcion">@Html.ActionLink("Volver", "ListaYDetalleMensaje", "Mensaje")</p>
					Chequeo.pagina = "";
				}
				else
				{
					<p class="parrafo-descripcion">@Html.ActionLink("Volver", "Index", "Home")</p>
				}
			</div>
		</div>
	</div>
</section>

Todo-Pallets/Views/Mensaje/DetalleMensaje.cshtml
@using Todo_Pallets.Models;

@{
	ViewBag.Titulo = "Detalles del mensaje";
}


<section>
	<div class="row">
		<div id="columna-descripcion-acerca">
			<div class="col-sm-6 columna">

				@if (ViewBag.mensaje != null)
				{
					<h1 id="descripcion">Detalles del mensaje:</h1>
					<p class="parrafo-descripcion">	<b>Nombre:</b> @ViewBag.mensaje.getNombre() <br />
																					<b>Apellido:</b> @ViewBag.mensaje.getApellido() <br />
																					<b>Email:</b> @ViewBag.mensaje.getEmail() </p>

					<p class="parrafo-descripcion"><b>Consulta:</b> @ViewBag.mensaje.getConsulta() </p>
				}
				else
				{
					<h1 id="descripcion">Error:</h1>
					<p class="parrafo-descripcion">No se pudo obtener los detalles de este mensaje.</p>
				}

				<p class="parrafo-descripcion">@Html.ActionLink("Volver", "ListaMensaje", "Mensaje")</p>

			</div>
		</div>
	</div>
</section>

Todo-Pallets/Views/Mensaje/ListaMensaje.cshtml
@using Todo_Pallets.Models;

@{
    ViewBag.Titulo = "Lista de Mensajes";
}


<section>
	<div class="row">
		<div id="columna-descripcion-acerca">
			<div class="col-sm-6 columna">
				<h1 id="descripcion">Lista de mensajes de contacto:</h1>

				<table id="tabla-mensajes" class="table table-hover">
					<thead>
						<tr class="fila-principal-tabla">
							<th>Nombre</th>
							<th>Apellido</th>
							<th>Email</th>
							<th>Operaciones</th>
						</tr>
					</thead>
					<tbody>
						@foreach (Mensajes msj in ViewBag.lstMensajes)
						{
							<tr>
								<td class="ancho-max">@msj.getNombre()</td>
								<td class="ancho-max">@msj.getApellido()</td>
								<td class="ancho-max">@msj.getEmail()</td>
								<td class="ancho-max">
									@Html.ActionLink("Detalles", "DetalleMensaje", new { id = msj.getID() })
									@Html.ActionLink("Borrar", "BorrarMensaje", new { id = msj.getID() })
								</td>
							</tr>
						}
					</tbody>
				</table>

			</div>
		</div>
	</div>
</section>

Todo-Pallets/Views/Mensaje/ListaYDetalleMensaje.cshtml
@using Todo_Pallets.Models;

@{
		ViewBag.Titulo = "Lista y detalles de los Mensajes";
}


<section>
	<div class="row">
		<div id="columna-descripcion-acerca">
			<div class="col-sm-6 columna">
				<h1 id="descripcion">Lista de mensajes de contacto:</h1>

				<table class="table table-hover tabla-mensajes">
					<thead>
						<tr class="fila-principal-tabla">
							<th>Nombre</th>
							<th>Apellido</th="filas">
							<th>Email</th>
							<th>Operaciones</th>
						</tr>
					</thead>
					<tbody>
						@foreach (Mensajes msj in ViewBag.lstMensajes)
						{
						<tr>
							<td class="ancho-max"> @msj.getNombre() </td>
							<td class="ancho-max"> @msj.getApellido() </td>
							<td class="ancho-max"> @msj.getEmail() </td>
							<td class="ancho-max">
								@Html.ActionLink("Detalles", "ListaYDetalleMensaje", new { id = msj.getID() })
								@Html.ActionLink("Borrar", "BorrarMensaje", new { id = msj.getID() })
							</td>
						</tr>
						}
					</tbody>
				</table>
			</div>

			<div class="col-sm-6 columna">

				@if (ViewBag.mensaje2 != null)
				{
					<h1 id="descripcion">Detalles del mensaje:</h1>
					<table class="table table-hover tabla-mensajes">
						<tbody>
							<tr class="fila-principal-tabla">
								<td class="ancho-fijo"><b>ID:</b></td>
								<td> @ViewBag.mensaje2.getID() </td>
							</tr>
							<tr>
								<td class="ancho-fijo"><b>Nombre:</b></td>
								<td> @ViewBag.mensaje2.getNombre() </td>
							</tr>
							<tr>
								<td class="ancho-fijo"><b>Apellido:</b></td>
								<td> @ViewBag.mensaje2.getApellido() </td>
							</tr>
							<tr>
								<td class="ancho-fijo"><b>Email:</b></td>
								<td> @ViewBag.mensaje2.getEmail() </td>
							</tr>
							<tr>
								<td class="ancho-fijo"><b>Consulta:</b></td>
								<td> @ViewBag.mensaje2.getConsulta() </td>
							</tr>
						</tbody>
					</table>
				}
				else
				{
					if (@ViewBag.mensajeID == null)
					{
						<h1 id="descripcion">Error:</h1>
						<p class="parrafo-descripcion">No se pudo obtener los detalles de este mensaje.</p>
					}
				}

			</div>
		</div>
	</div>
</section>

Todo-Pallets/Views/Mensaje/MandarMensaje.cshtml

@{
    ViewBag.Titulo = "MensajeEnviar";
}

<section>
	<div class="row">
		<div id="columna-descripcion-acerca">
			<div class="col-sm-6 columna">
				<h1 id="descripcion">Resultados del envio de la consulta:</h1>
				<p class="parrafo-descripcion">@ViewBag.resultadoMensaje</p>
				<p class="parrafo-descripcion"></p>
				<p class="parrafo-descripcion">@Html.ActionLink("Volver", "Contacto", "Home")</p>

			</div>
		</div>
	</div>
</section>